#!/usr/bin/env bash
trap "echo I hate the kill command; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "exit" SIGQUIT

echo $$ > /var/run/myscript.pid

while true; do
	echo "To infinity amd beyond"
done
