#!/usr/bin/env bash
#more advanced tasks
trap "rm /var/run/myscript.pid; exit" SIGQUIT
trap "echo I hate the kill command; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
echo $$ > /var/run/myscript.pid
while true; do
	echo To infinity amd beyond
	sleep 2
done
